### ISSUE TITLE
Preview does not render if CSL in YAML is not absolute path.

### ISSUE THREAD

**Issue by kmwallio** [kmwallio/ThiefMD#135]
Currently:

```yaml
---
bibliography: bib.bib
csl: bib_style.csl
---
```

will cause the preview to fail.

```yaml
---
bibliography: bib.bib
csl: /home/user/path/to/bib_style.csl
---
```

will work.

This will be fixed in the next release.
